//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsronomicheskiyKalendar.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstronomicalObservations
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public Nullable<int> IdVisibilityOfPlanets { get; set; }
        public Nullable<int> IdLenghtOfDayAndNight { get; set; }
        public Nullable<int> IdStarfalls { get; set; }
        public Nullable<int> IdEclipses { get; set; }
        public Nullable<int> IdMoonType { get; set; }
    
        public virtual Eclipses Eclipses { get; set; }
        public virtual LengthOfDayAndNight LengthOfDayAndNight { get; set; }
        public virtual MoonType MoonType { get; set; }
        public virtual Starfalls Starfalls { get; set; }
        public virtual VisibilityOfPlanets VisibilityOfPlanets { get; set; }
    }
}
